apiVersion: v1
kind: Service
metadata:
  labels:
    team: naisdevice
  name: kolide-event-handler-grpc
  namespace: naisdevice
spec:
  ports:
  - name: grpc
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: kolide-event-handler
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: gw-nais-io
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/use-regex: "true"
  labels:
    team: naisdevice
  name: kolide-event-handler-grpc
  namespace: naisdevice
spec:
  rules:
  - host: kolide-event-handler-grpc.prod-gcp.nais.io
    http:
      paths:
      - backend:
          serviceName: kolide-event-handler-grpc
          servicePort: 8081
        path: /
