apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "kolide-event-handler"
  namespace: "nais"
  labels:
    "team": "nais"
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 2
    timeout: 2
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 2
    timeout: 2
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  resources:
    requests:
      cpu: "20m"
      memory: "128Mi"
  envFrom:
    - secret: kolide-event-handler
  accessPolicy:
    outbound:
      external:
        - host: k2.kolide.com
        - host: api.kolide.com
  ingresses:
    - "https://kolide-event-handler.external.prod-gcp.nav.cloud.nais.io/webhooks"
