apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "kolide-event-handler"
  namespace: "naisdevice"
  labels:
    "team": "naisdevice"
spec:
  image: {{image}}
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 2
    timeout: 2
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 2
    timeout: 2
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "20m"
    memory: "32Mi"
  envFrom:
    - secret: kolide-event-handler
  accessPolicy:
    outbound:
      external:
        - host: k2.kolide.com
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
