apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kolide-event-handler.fullname" . }}
  labels:
    {{- include "kolide-event-handler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kolide-event-handler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kolide-event-handler.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: kolide-event-handler
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /isalive
              port: http
          readinessProbe:
            httpGet:
              path: /isready
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
