apiVersion: v1
kind: Service
metadata:
  name: {{ include "kolide-event-handler.fullname" . }}
  labels:
    {{- include "kolide-event-handler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "kolide-event-handler.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: kolide-event-handler-grpc
  labels:
    {{- include "kolide-event-handler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    {{- include "kolide-event-handler.selectorLabels" . | nindent 4 }}
