secrets:
  env:
    KOLIDE_SIGNING_SECRET: ""
    KOLIDE_API_TOKEN: ""
    GRPC_AUTH_TOKEN: ""

replicaCount: 1

image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/kolide-event-handler
  pullPolicy: IfNotPresent
  tag: main

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nais-ingress
  hosts: []

resources:
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "20m"
    memory: "32Mi"

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
