// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/pb/kolide-event-handler.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsRequest) Reset() {
	*x = EventsRequest{}
	mi := &file_pkg_pb_kolide_event_handler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsRequest) ProtoMessage() {}

func (x *EventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_kolide_event_handler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsRequest.ProtoReflect.Descriptor instead.
func (*EventsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_kolide_event_handler_proto_rawDescGZIP(), []int{0}
}

type DeviceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExternalID    string                 `protobuf:"bytes,6,opt,name=externalID,proto3" json:"externalID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceEvent) Reset() {
	*x = DeviceEvent{}
	mi := &file_pkg_pb_kolide_event_handler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceEvent) ProtoMessage() {}

func (x *DeviceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_kolide_event_handler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceEvent.ProtoReflect.Descriptor instead.
func (*DeviceEvent) Descriptor() ([]byte, []int) {
	return file_pkg_pb_kolide_event_handler_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *DeviceEvent) GetExternalID() string {
	if x != nil {
		return x.ExternalID
	}
	return ""
}

var File_pkg_pb_kolide_event_handler_proto protoreflect.FileDescriptor

const file_pkg_pb_kolide_event_handler_proto_rawDesc = "" +
	"\n" +
	"!pkg/pb/kolide-event-handler.proto\x12\x14kolide_event_handler\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rEventsRequest\"\x7f\n" +
	"\vDeviceEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1e\n" +
	"\n" +
	"externalID\x18\x06 \x01(\tR\n" +
	"externalIDJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x062j\n" +
	"\x12KolideEventHandler\x12T\n" +
	"\x06Events\x12#.kolide_event_handler.EventsRequest\x1a!.kolide_event_handler.DeviceEvent\"\x000\x01B-Z+github.com/nais/kolide-event-handler/pkg/pbb\x06proto3"

var (
	file_pkg_pb_kolide_event_handler_proto_rawDescOnce sync.Once
	file_pkg_pb_kolide_event_handler_proto_rawDescData []byte
)

func file_pkg_pb_kolide_event_handler_proto_rawDescGZIP() []byte {
	file_pkg_pb_kolide_event_handler_proto_rawDescOnce.Do(func() {
		file_pkg_pb_kolide_event_handler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_kolide_event_handler_proto_rawDesc), len(file_pkg_pb_kolide_event_handler_proto_rawDesc)))
	})
	return file_pkg_pb_kolide_event_handler_proto_rawDescData
}

var file_pkg_pb_kolide_event_handler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_kolide_event_handler_proto_goTypes = []any{
	(*EventsRequest)(nil),         // 0: kolide_event_handler.EventsRequest
	(*DeviceEvent)(nil),           // 1: kolide_event_handler.DeviceEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_pb_kolide_event_handler_proto_depIdxs = []int32{
	2, // 0: kolide_event_handler.DeviceEvent.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: kolide_event_handler.KolideEventHandler.Events:input_type -> kolide_event_handler.EventsRequest
	1, // 2: kolide_event_handler.KolideEventHandler.Events:output_type -> kolide_event_handler.DeviceEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_pb_kolide_event_handler_proto_init() }
func file_pkg_pb_kolide_event_handler_proto_init() {
	if File_pkg_pb_kolide_event_handler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_kolide_event_handler_proto_rawDesc), len(file_pkg_pb_kolide_event_handler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_kolide_event_handler_proto_goTypes,
		DependencyIndexes: file_pkg_pb_kolide_event_handler_proto_depIdxs,
		MessageInfos:      file_pkg_pb_kolide_event_handler_proto_msgTypes,
	}.Build()
	File_pkg_pb_kolide_event_handler_proto = out.File
	file_pkg_pb_kolide_event_handler_proto_goTypes = nil
	file_pkg_pb_kolide_event_handler_proto_depIdxs = nil
}
